FROM node:20-alpine

WORKDIR /app

# Install Angular CLI globally
RUN npm install -g @angular/cli

# Disable Angular analytics
ENV NG_CLI_ANALYTICS=false

EXPOSE 4200

# Default command - can be overridden
CMD ["sh"]
